services:
  tipiak:
    image: ghcr.io/zool-rig/tipiak:latest
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - TIPIAK_APP_CONFIG_PATH=/config/tipiak_app.toml
    volumes:
      - /home/pi/tipiak/tipiak_app.toml:/config/tipiak_app.toml:ro
      - /home/pi/tipiak/storage:/data/storage:ro