name: Code Quality

on:
  push:

jobs:
  rust-clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.88.0
          components: clippy

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings