name: Format

on:
  push:

jobs:
  rust-fmt:
    name: Cargo Fmt Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.88.0
          components: rustfmt

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Check Rust formatting
        run: cargo fmt --all --check